//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Middle.SoapJava {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://communication.mycompany.com/", ConfigurationName="SoapJava.CommunicationEndPoint")]
    public interface CommunicationEndPoint {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément userToken de l'espace de noms  n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://communication.mycompany.com/CommunicationEndPoint/SendDecryptFileRequest", ReplyAction="http://communication.mycompany.com/CommunicationEndPoint/SendDecryptFileResponse")]
        Middle.SoapJava.SendDecryptFileResponse SendDecryptFile(Middle.SoapJava.SendDecryptFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://communication.mycompany.com/CommunicationEndPoint/SendDecryptFileRequest", ReplyAction="http://communication.mycompany.com/CommunicationEndPoint/SendDecryptFileResponse")]
        System.Threading.Tasks.Task<Middle.SoapJava.SendDecryptFileResponse> SendDecryptFileAsync(Middle.SoapJava.SendDecryptFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDecryptFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDecryptFile", Namespace="http://communication.mycompany.com/", Order=0)]
        public Middle.SoapJava.SendDecryptFileRequestBody Body;
        
        public SendDecryptFileRequest() {
        }
        
        public SendDecryptFileRequest(Middle.SoapJava.SendDecryptFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendDecryptFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string decryptFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nameFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string keyDecryptFile;
        
        public SendDecryptFileRequestBody() {
        }
        
        public SendDecryptFileRequestBody(string userToken, string decryptFile, string nameFile, string keyDecryptFile) {
            this.userToken = userToken;
            this.decryptFile = decryptFile;
            this.nameFile = nameFile;
            this.keyDecryptFile = keyDecryptFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendDecryptFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendDecryptFileResponse", Namespace="http://communication.mycompany.com/", Order=0)]
        public Middle.SoapJava.SendDecryptFileResponseBody Body;
        
        public SendDecryptFileResponse() {
        }
        
        public SendDecryptFileResponse(Middle.SoapJava.SendDecryptFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SendDecryptFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DecryptValidation;
        
        public SendDecryptFileResponseBody() {
        }
        
        public SendDecryptFileResponseBody(bool DecryptValidation) {
            this.DecryptValidation = DecryptValidation;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommunicationEndPointChannel : Middle.SoapJava.CommunicationEndPoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommunicationEndPointClient : System.ServiceModel.ClientBase<Middle.SoapJava.CommunicationEndPoint>, Middle.SoapJava.CommunicationEndPoint {
        
        public CommunicationEndPointClient() {
        }
        
        public CommunicationEndPointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommunicationEndPointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationEndPointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommunicationEndPointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Middle.SoapJava.SendDecryptFileResponse Middle.SoapJava.CommunicationEndPoint.SendDecryptFile(Middle.SoapJava.SendDecryptFileRequest request) {
            return base.Channel.SendDecryptFile(request);
        }
        
        public bool SendDecryptFile(string userToken, string decryptFile, string nameFile, string keyDecryptFile) {
            Middle.SoapJava.SendDecryptFileRequest inValue = new Middle.SoapJava.SendDecryptFileRequest();
            inValue.Body = new Middle.SoapJava.SendDecryptFileRequestBody();
            inValue.Body.userToken = userToken;
            inValue.Body.decryptFile = decryptFile;
            inValue.Body.nameFile = nameFile;
            inValue.Body.keyDecryptFile = keyDecryptFile;
            Middle.SoapJava.SendDecryptFileResponse retVal = ((Middle.SoapJava.CommunicationEndPoint)(this)).SendDecryptFile(inValue);
            return retVal.Body.DecryptValidation;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Middle.SoapJava.SendDecryptFileResponse> Middle.SoapJava.CommunicationEndPoint.SendDecryptFileAsync(Middle.SoapJava.SendDecryptFileRequest request) {
            return base.Channel.SendDecryptFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<Middle.SoapJava.SendDecryptFileResponse> SendDecryptFileAsync(string userToken, string decryptFile, string nameFile, string keyDecryptFile) {
            Middle.SoapJava.SendDecryptFileRequest inValue = new Middle.SoapJava.SendDecryptFileRequest();
            inValue.Body = new Middle.SoapJava.SendDecryptFileRequestBody();
            inValue.Body.userToken = userToken;
            inValue.Body.decryptFile = decryptFile;
            inValue.Body.nameFile = nameFile;
            inValue.Body.keyDecryptFile = keyDecryptFile;
            return ((Middle.SoapJava.CommunicationEndPoint)(this)).SendDecryptFileAsync(inValue);
        }
    }
}
